set tabstop=4
"set cursorbind
set ruler
"set helplang=cn
colorscheme peachpuff
"VIMWiki
"不兼容VI
set nocompatible
filetype on
"识别文件类型
filetype plugin on
"语法增强
syntax on

"显示/隐藏行光标线
let s:row=1
function! Set_Cursorline()
	if exists("s:row")
		set cursorline
		unlet s:row
	else
		set nocursorline
		let s:row=1
	endif
endfunction
"显示/隐藏列光标线
let s:column=1
function! Set_Cursorcolumn()
	if exists("s:column")
		set cursorcolumn
		unlet s:column
	else
		set nocursorcolumn
		let s:column=1
	endif
endfunction

"显示/隐藏行号
let s:num=1
function! Set_Num()
	if exists("s:num")
		set number
		unlet s:num
	else
		set nonumber
		let s:num=1
	endif
endfunction
nmap ,n :call Set_Num()<CR>
nmap ,r :call Set_Cursorline()<CR>
nmap ,c :call Set_Cursorcolumn()<CR>
"使.vimrc配置生效
nmap ,s :source $HOME/.vimrc<cr>
"打开标签页面的个数
set tabpagemax=5
"显示标签页:0不显示,1创建后显示，2总是显示标签栏
set showtabline=1
"markdown
"let g:vim_markdown_folding_disabled=1
au BufRead,BufNewFile *.{md,mdown,mkd,mkdn,markdown,mdwn} set filetype=mkd

"插入当前时间
nmap ,d "=strftime("%Y-%m-%d %H:%M:%S")<CR>p

				
